theme: minima
title: divertidos games
author: mikhail shchegolkov
description: This blog is about developing a website with a database of game mechanics and other elements that can be used in games.
